spring.application.name=finance-tracker

#Postgres connection details
spring.datasource.url=jdbc:postgresql://localhost:5432/finance-db
spring.datasource.username=postgres
spring.datasource.password=loveMom@1997
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#GraphQL configuration